package main

import (
	"log"
	"os"
	"path/filepath"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	// 设置生成选项
	opts := []entc.Option{
		entc.TemplateDir("../../ent/template"),
		entc.HeaderFile("../../ent/header"),
	}

	// 为每个实体创建单独的目录
	if err := entc.Generate("../../ent/schema", &gen.Config{
		Target:  "../../ent/generated",
		Package: "generated",
		Header:  "// Code generated by entc, DO NOT EDIT.",
	}, opts...); err != nil {
		log.Fatal("running ent codegen:", err)
	}

	// 创建实体目录
	entities := []string{"fruitprice"} // 添加更多实体名称
	for _, entity := range entities {
		dir := filepath.Join("../../ent/generated", entity)
		if err := os.MkdirAll(dir, 0755); err != nil {
			log.Fatal("creating entity directory:", err)
		}
	}
}
