// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FruitPricesColumns holds the columns for the "fruit_prices" table.
	FruitPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "unit", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FruitPricesTable holds the schema information for the "fruit_prices" table.
	FruitPricesTable = &schema.Table{
		Name:       "fruit_prices",
		Columns:    FruitPricesColumns,
		PrimaryKey: []*schema.Column{FruitPricesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FruitPricesTable,
	}
)

func init() {
}
