// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"api-go-ent/ent/migrate"

	"api-go-ent/ent/fruitprice"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FruitPrice is the client for interacting with the FruitPrice builders.
	FruitPrice *FruitPriceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FruitPrice = NewFruitPriceClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		FruitPrice: NewFruitPriceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		FruitPrice: NewFruitPriceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FruitPrice.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FruitPrice.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.FruitPrice.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FruitPriceMutation:
		return c.FruitPrice.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FruitPriceClient is a client for the FruitPrice schema.
type FruitPriceClient struct {
	config
}

// NewFruitPriceClient returns a client for the FruitPrice from the given config.
func NewFruitPriceClient(c config) *FruitPriceClient {
	return &FruitPriceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fruitprice.Hooks(f(g(h())))`.
func (c *FruitPriceClient) Use(hooks ...Hook) {
	c.hooks.FruitPrice = append(c.hooks.FruitPrice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fruitprice.Intercept(f(g(h())))`.
func (c *FruitPriceClient) Intercept(interceptors ...Interceptor) {
	c.inters.FruitPrice = append(c.inters.FruitPrice, interceptors...)
}

// Create returns a builder for creating a FruitPrice entity.
func (c *FruitPriceClient) Create() *FruitPriceCreate {
	mutation := newFruitPriceMutation(c.config, OpCreate)
	return &FruitPriceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FruitPrice entities.
func (c *FruitPriceClient) CreateBulk(builders ...*FruitPriceCreate) *FruitPriceCreateBulk {
	return &FruitPriceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FruitPriceClient) MapCreateBulk(slice any, setFunc func(*FruitPriceCreate, int)) *FruitPriceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FruitPriceCreateBulk{err: fmt.Errorf("calling to FruitPriceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FruitPriceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FruitPriceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FruitPrice.
func (c *FruitPriceClient) Update() *FruitPriceUpdate {
	mutation := newFruitPriceMutation(c.config, OpUpdate)
	return &FruitPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FruitPriceClient) UpdateOne(fp *FruitPrice) *FruitPriceUpdateOne {
	mutation := newFruitPriceMutation(c.config, OpUpdateOne, withFruitPrice(fp))
	return &FruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FruitPriceClient) UpdateOneID(id uuid.UUID) *FruitPriceUpdateOne {
	mutation := newFruitPriceMutation(c.config, OpUpdateOne, withFruitPriceID(id))
	return &FruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FruitPrice.
func (c *FruitPriceClient) Delete() *FruitPriceDelete {
	mutation := newFruitPriceMutation(c.config, OpDelete)
	return &FruitPriceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FruitPriceClient) DeleteOne(fp *FruitPrice) *FruitPriceDeleteOne {
	return c.DeleteOneID(fp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FruitPriceClient) DeleteOneID(id uuid.UUID) *FruitPriceDeleteOne {
	builder := c.Delete().Where(fruitprice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FruitPriceDeleteOne{builder}
}

// Query returns a query builder for FruitPrice.
func (c *FruitPriceClient) Query() *FruitPriceQuery {
	return &FruitPriceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFruitPrice},
		inters: c.Interceptors(),
	}
}

// Get returns a FruitPrice entity by its id.
func (c *FruitPriceClient) Get(ctx context.Context, id uuid.UUID) (*FruitPrice, error) {
	return c.Query().Where(fruitprice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FruitPriceClient) GetX(ctx context.Context, id uuid.UUID) *FruitPrice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FruitPriceClient) Hooks() []Hook {
	return c.hooks.FruitPrice
}

// Interceptors returns the client interceptors.
func (c *FruitPriceClient) Interceptors() []Interceptor {
	return c.inters.FruitPrice
}

func (c *FruitPriceClient) mutate(ctx context.Context, m *FruitPriceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FruitPriceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FruitPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FruitPriceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FruitPrice mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		FruitPrice []ent.Hook
	}
	inters struct {
		FruitPrice []ent.Interceptor
	}
)
