// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api-go-ent/ent/fruitprice"
	"api-go-ent/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FruitPriceDelete is the builder for deleting a FruitPrice entity.
type FruitPriceDelete struct {
	config
	hooks    []Hook
	mutation *FruitPriceMutation
}

// Where appends a list predicates to the FruitPriceDelete builder.
func (fpd *FruitPriceDelete) Where(ps ...predicate.FruitPrice) *FruitPriceDelete {
	fpd.mutation.Where(ps...)
	return fpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fpd *FruitPriceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fpd.sqlExec, fpd.mutation, fpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fpd *FruitPriceDelete) ExecX(ctx context.Context) int {
	n, err := fpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fpd *FruitPriceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fruitprice.Table, sqlgraph.NewFieldSpec(fruitprice.FieldID, field.TypeUUID))
	if ps := fpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fpd.mutation.done = true
	return affected, err
}

// FruitPriceDeleteOne is the builder for deleting a single FruitPrice entity.
type FruitPriceDeleteOne struct {
	fpd *FruitPriceDelete
}

// Where appends a list predicates to the FruitPriceDelete builder.
func (fpdo *FruitPriceDeleteOne) Where(ps ...predicate.FruitPrice) *FruitPriceDeleteOne {
	fpdo.fpd.mutation.Where(ps...)
	return fpdo
}

// Exec executes the deletion query.
func (fpdo *FruitPriceDeleteOne) Exec(ctx context.Context) error {
	n, err := fpdo.fpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fruitprice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fpdo *FruitPriceDeleteOne) ExecX(ctx context.Context) {
	if err := fpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
