// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api-go-ent/ent/fruitprice"
	"api-go-ent/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FruitPriceQuery is the builder for querying FruitPrice entities.
type FruitPriceQuery struct {
	config
	ctx        *QueryContext
	order      []fruitprice.OrderOption
	inters     []Interceptor
	predicates []predicate.FruitPrice
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FruitPriceQuery builder.
func (fpq *FruitPriceQuery) Where(ps ...predicate.FruitPrice) *FruitPriceQuery {
	fpq.predicates = append(fpq.predicates, ps...)
	return fpq
}

// Limit the number of records to be returned by this query.
func (fpq *FruitPriceQuery) Limit(limit int) *FruitPriceQuery {
	fpq.ctx.Limit = &limit
	return fpq
}

// Offset to start from.
func (fpq *FruitPriceQuery) Offset(offset int) *FruitPriceQuery {
	fpq.ctx.Offset = &offset
	return fpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fpq *FruitPriceQuery) Unique(unique bool) *FruitPriceQuery {
	fpq.ctx.Unique = &unique
	return fpq
}

// Order specifies how the records should be ordered.
func (fpq *FruitPriceQuery) Order(o ...fruitprice.OrderOption) *FruitPriceQuery {
	fpq.order = append(fpq.order, o...)
	return fpq
}

// First returns the first FruitPrice entity from the query.
// Returns a *NotFoundError when no FruitPrice was found.
func (fpq *FruitPriceQuery) First(ctx context.Context) (*FruitPrice, error) {
	nodes, err := fpq.Limit(1).All(setContextOp(ctx, fpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fruitprice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fpq *FruitPriceQuery) FirstX(ctx context.Context) *FruitPrice {
	node, err := fpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FruitPrice ID from the query.
// Returns a *NotFoundError when no FruitPrice ID was found.
func (fpq *FruitPriceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fpq.Limit(1).IDs(setContextOp(ctx, fpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fruitprice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fpq *FruitPriceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := fpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FruitPrice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FruitPrice entity is found.
// Returns a *NotFoundError when no FruitPrice entities are found.
func (fpq *FruitPriceQuery) Only(ctx context.Context) (*FruitPrice, error) {
	nodes, err := fpq.Limit(2).All(setContextOp(ctx, fpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fruitprice.Label}
	default:
		return nil, &NotSingularError{fruitprice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fpq *FruitPriceQuery) OnlyX(ctx context.Context) *FruitPrice {
	node, err := fpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FruitPrice ID in the query.
// Returns a *NotSingularError when more than one FruitPrice ID is found.
// Returns a *NotFoundError when no entities are found.
func (fpq *FruitPriceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fpq.Limit(2).IDs(setContextOp(ctx, fpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fruitprice.Label}
	default:
		err = &NotSingularError{fruitprice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fpq *FruitPriceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := fpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FruitPrices.
func (fpq *FruitPriceQuery) All(ctx context.Context) ([]*FruitPrice, error) {
	ctx = setContextOp(ctx, fpq.ctx, ent.OpQueryAll)
	if err := fpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FruitPrice, *FruitPriceQuery]()
	return withInterceptors[[]*FruitPrice](ctx, fpq, qr, fpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fpq *FruitPriceQuery) AllX(ctx context.Context) []*FruitPrice {
	nodes, err := fpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FruitPrice IDs.
func (fpq *FruitPriceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if fpq.ctx.Unique == nil && fpq.path != nil {
		fpq.Unique(true)
	}
	ctx = setContextOp(ctx, fpq.ctx, ent.OpQueryIDs)
	if err = fpq.Select(fruitprice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fpq *FruitPriceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := fpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fpq *FruitPriceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fpq.ctx, ent.OpQueryCount)
	if err := fpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fpq, querierCount[*FruitPriceQuery](), fpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fpq *FruitPriceQuery) CountX(ctx context.Context) int {
	count, err := fpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fpq *FruitPriceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fpq.ctx, ent.OpQueryExist)
	switch _, err := fpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fpq *FruitPriceQuery) ExistX(ctx context.Context) bool {
	exist, err := fpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FruitPriceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fpq *FruitPriceQuery) Clone() *FruitPriceQuery {
	if fpq == nil {
		return nil
	}
	return &FruitPriceQuery{
		config:     fpq.config,
		ctx:        fpq.ctx.Clone(),
		order:      append([]fruitprice.OrderOption{}, fpq.order...),
		inters:     append([]Interceptor{}, fpq.inters...),
		predicates: append([]predicate.FruitPrice{}, fpq.predicates...),
		// clone intermediate query.
		sql:  fpq.sql.Clone(),
		path: fpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FruitPrice.Query().
//		GroupBy(fruitprice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fpq *FruitPriceQuery) GroupBy(field string, fields ...string) *FruitPriceGroupBy {
	fpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FruitPriceGroupBy{build: fpq}
	grbuild.flds = &fpq.ctx.Fields
	grbuild.label = fruitprice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FruitPrice.Query().
//		Select(fruitprice.FieldCreatedAt).
//		Scan(ctx, &v)
func (fpq *FruitPriceQuery) Select(fields ...string) *FruitPriceSelect {
	fpq.ctx.Fields = append(fpq.ctx.Fields, fields...)
	sbuild := &FruitPriceSelect{FruitPriceQuery: fpq}
	sbuild.label = fruitprice.Label
	sbuild.flds, sbuild.scan = &fpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FruitPriceSelect configured with the given aggregations.
func (fpq *FruitPriceQuery) Aggregate(fns ...AggregateFunc) *FruitPriceSelect {
	return fpq.Select().Aggregate(fns...)
}

func (fpq *FruitPriceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fpq); err != nil {
				return err
			}
		}
	}
	for _, f := range fpq.ctx.Fields {
		if !fruitprice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fpq.path != nil {
		prev, err := fpq.path(ctx)
		if err != nil {
			return err
		}
		fpq.sql = prev
	}
	return nil
}

func (fpq *FruitPriceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FruitPrice, error) {
	var (
		nodes = []*FruitPrice{}
		_spec = fpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FruitPrice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FruitPrice{config: fpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fpq *FruitPriceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fpq.querySpec()
	_spec.Node.Columns = fpq.ctx.Fields
	if len(fpq.ctx.Fields) > 0 {
		_spec.Unique = fpq.ctx.Unique != nil && *fpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fpq.driver, _spec)
}

func (fpq *FruitPriceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fruitprice.Table, fruitprice.Columns, sqlgraph.NewFieldSpec(fruitprice.FieldID, field.TypeUUID))
	_spec.From = fpq.sql
	if unique := fpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fpq.path != nil {
		_spec.Unique = true
	}
	if fields := fpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fruitprice.FieldID)
		for i := range fields {
			if fields[i] != fruitprice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fpq *FruitPriceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fpq.driver.Dialect())
	t1 := builder.Table(fruitprice.Table)
	columns := fpq.ctx.Fields
	if len(columns) == 0 {
		columns = fruitprice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fpq.sql != nil {
		selector = fpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fpq.ctx.Unique != nil && *fpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fpq.predicates {
		p(selector)
	}
	for _, p := range fpq.order {
		p(selector)
	}
	if offset := fpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FruitPriceGroupBy is the group-by builder for FruitPrice entities.
type FruitPriceGroupBy struct {
	selector
	build *FruitPriceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fpgb *FruitPriceGroupBy) Aggregate(fns ...AggregateFunc) *FruitPriceGroupBy {
	fpgb.fns = append(fpgb.fns, fns...)
	return fpgb
}

// Scan applies the selector query and scans the result into the given value.
func (fpgb *FruitPriceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fpgb.build.ctx, ent.OpQueryGroupBy)
	if err := fpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FruitPriceQuery, *FruitPriceGroupBy](ctx, fpgb.build, fpgb, fpgb.build.inters, v)
}

func (fpgb *FruitPriceGroupBy) sqlScan(ctx context.Context, root *FruitPriceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fpgb.fns))
	for _, fn := range fpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fpgb.flds)+len(fpgb.fns))
		for _, f := range *fpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FruitPriceSelect is the builder for selecting fields of FruitPrice entities.
type FruitPriceSelect struct {
	*FruitPriceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fps *FruitPriceSelect) Aggregate(fns ...AggregateFunc) *FruitPriceSelect {
	fps.fns = append(fps.fns, fns...)
	return fps
}

// Scan applies the selector query and scans the result into the given value.
func (fps *FruitPriceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fps.ctx, ent.OpQuerySelect)
	if err := fps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FruitPriceQuery, *FruitPriceSelect](ctx, fps.FruitPriceQuery, fps, fps.inters, v)
}

func (fps *FruitPriceSelect) sqlScan(ctx context.Context, root *FruitPriceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fps.fns))
	for _, fn := range fps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
