// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FruitPrice is the predicate function for fruitprice builders.
type FruitPrice func(*sql.Selector)
